// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.cyberinternauts.all.MediaRecognizer.Database;

#nullable disable

namespace com.cyberinternauts.all.MediaRecognizer.Migrations
{
    [DbContext(typeof(MediaRecognizerContext))]
    [Migration("20220210162516_InitialContext")]
    partial class InitialContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("com.cyberinternauts.all.MediaRecognizer.Models.Medias.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("com.cyberinternauts.all.MediaRecognizer.Models.Medias.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("com.cyberinternauts.all.MediaRecognizer.Models.Metas.MetaMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetaSource");

                    b.HasIndex("Title");

                    b.HasIndex("TotalMinutes");

                    b.HasIndex("ExternalId", "MetaSource")
                        .IsUnique();

                    b.ToTable("MetaMovies");
                });

            modelBuilder.Entity("com.cyberinternauts.all.MediaRecognizer.Models.Metas.MetaTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetaMovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("MetaMovieId");

                    b.ToTable("MetaTitles");
                });

            modelBuilder.Entity("com.cyberinternauts.all.MediaRecognizer.Models.Medias.Title", b =>
                {
                    b.HasOne("com.cyberinternauts.all.MediaRecognizer.Models.Medias.Movie", "Movie")
                        .WithMany("Titles")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("com.cyberinternauts.all.MediaRecognizer.Models.Metas.MetaTitle", b =>
                {
                    b.HasOne("com.cyberinternauts.all.MediaRecognizer.Models.Metas.MetaMovie", "MetaMovie")
                        .WithMany("Titles")
                        .HasForeignKey("MetaMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaMovie");
                });

            modelBuilder.Entity("com.cyberinternauts.all.MediaRecognizer.Models.Medias.Movie", b =>
                {
                    b.Navigation("Titles");
                });

            modelBuilder.Entity("com.cyberinternauts.all.MediaRecognizer.Models.Metas.MetaMovie", b =>
                {
                    b.Navigation("Titles");
                });
#pragma warning restore 612, 618
        }
    }
}
